### ISSUE TITLE
Brainstorm the new design for the IDMS data fellowship program

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/datafellowship#1]
The idea is to have a simple fellowship page for the IDMS data fellowship program, which can be used for promotion and marketing.

**TODO**

- [x] Brainstorm the idea for the design in the docs: https://docs.google.com/document/d/1cphBiTJDaz7lHP4bnn33BszMysVPd4db_SBf7R5KTt4/edit?usp=sharing
- [x] Find the suitable template
- [x] Develop the new fellowship page
- [x] Move the old fellowship somewhere (probably in the dropdown of the new page)
- [x] Submit change for the review

**Comment by nikeshbalami** [comment]
DONE
