### ISSUE TITLE
Add new fellows bios and photos to fellowship website

### ISSUE THREAD

**Issue by Zaymes** [okfnepal/datafellowship#4]
We have onboarded the new fellows for Janakpurdham Sub-Metropolitan City and Suddhodhan Rural Municipality. Now, we have to add the fellow's bios to the lg data fellowship website. The contents for photo and bios can be found here: https://drive.google.com/drive/folders/1tDfoxANZYhI1oiTsXmpSHv2DPad_45ik

### Acceptance criteria

- [x] I have updated the fellowship website with added the fellow's information.

### Tasks

- [x] Collect the photos and bios from fellows
- [x] Update bio and photos in the fellows section of website
- [x] Deploy the changes in the website

**Comment by nikeshbalami** [comment]
Let's also make social media posts introducing the data fellow like the previous year.

**Comment by Zaymes** [comment]
Fellows' bios and photos are updated
https://fellowship.oknp.org/
